---
name: "\U0001F41B Bug report"
description: Bug report
title: "\U0001F41B: [Insert your bug name here]"
labels: ["bug", "triage"]

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: What exactly went wrong of what bug did you encounter?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce the bug?
      description: How do you trigger this bug? Please walk us through it step by step in detail. This is crucial in order to triage the bug and support you in resolving it.
    validations:
      required: true
    
  - type: textarea
    attributes:
      label: (Optional) Additional information
      description: Add any additional information that might help with this bug report.
    validations:
      required: false
      
  - type: input
    attributes:
      label: (Optional) Error message
      description: If you encountered any error message, copy and paste it here. This will be used for googling the issue.
    validations:
      required: false
