---
name: "\U0001F4DD Documentation"
description: Something is missing or wrong in the documentation.
title: "\U0001F4DD: [Insert your documentation error name here]"
labels: ["documentation"]

body:

  - type: textarea
    attributes:
      label: What is wrong in the documentation?
      description: Tell us, what is wrong in the documentation?
    validations:
      required: true

  - type: textarea
    attributes:
      label: (Optional) Additional information
      description: Add any additional information that might help with this bug report (E.g. input your obtained response.).
    validations:
      required: false
