---
name: "\U0001F4DD Documentation"
description: Something is missing or wrong in the documentation.
title: "\U0001F4DD [Insert your documentation error name here]: "
labels: ["documentation"]

body:

  - type: textarea
    attributes:
      label: What is wrong in the documentation?
      description: Tell us, what is wrong in the documentation?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Add more information
      description: here you can put extra information for this error. (e.g input your obtained response)
    validations:
      required: false
