blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/orgs/community/discussions
    about: Report a bug with existing JWT-PROJECT features.
  - name: Documentation Feedback
    url: https://bounty.github.com/
    about: Report an issue with the firebase.google.com/docs/flutter documentation or suggest an improvement.
  - name: Report a security vulnerability
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
